#159961949 Sign Up Feature
andela/ah-jarvis-frontend pull request #15
Opened 2018-09-07 08:25 UTC by asamisellah

#### What does this PR do?
Allows users to create an account with authors' haven.

#### Description of Task to be completed?
- Create sign up components
- Develop actions for the sign-up component
- Develop reducer for the sign-up component
- Make input field dynamic to guide user on criteria expected
- Write tests for sign up feature

#### How should this be manually tested?
##### Prerequisites 
Node and NPM should be installed.

##### Steps

1. Clone this repo and branch `git clone git@github.com:andela/ah-jarvis-frontend.git  -b ft-signup-159961949`
2. Open the project in your prefered text editor
3. Run the code below in your terminal

```
yarn install

yarn start

```
4. You should be redirected to your browser
5. Navigate to this url: http://localhost:3000/signup
6. The sign up page should appear as below
<img width="1277" alt="screen shot 2018-09-07 at 11 17 45 am" src="https://user-images.githubusercontent.com/13402544/45207347-68516680-b290-11e8-9454-99d8b855a287.png">

#### Running tests
To run the tests use the following command in your terminal:
``` yarn test --coverage```

### Screenshots
<img width="1280" alt="screen shot 2018-09-11 at 3 10 03 pm" src="https://user-images.githubusercontent.com/13402544/45359410-251b2e80-b5d5-11e8-8c83-a0bfb7bfe032.png">

<img width="1277" alt="screen shot 2018-09-11 at 3 10 46 pm" src="https://user-images.githubusercontent.com/13402544/45359415-277d8880-b5d5-11e8-840e-efcc5095e701.png">

#### Any background context you want to provide?
None

#### What are the relevant pivotal tracker stories?
[#159961949](https://www.pivotaltracker.com/story/show/159961949/comments/193936568)

2018-09-07 09:05 UTC, yeenab requested changes
Checks are failing

2018-09-07 09:42 UTC, asamisellah commented
@j33n  I'm fixing the problems with the linter

2018-09-11 07:23 UTC, yeenab requested changes
### Nitpicks

2018-09-11 07:23 UTC, yeenab commented on src/components/SignUpForm/index.js
> +            : ""}
Let's de-structure here, also, you can do something like this to keep your code clean:

```
const { failure, errors } = this.props.register;

{failure && errors.errors.username}
```

2018-09-11 07:23 UTC, yeenab commented on src/components/SignUpForm/index.js
> +        <p className="p-t--10 p-b--10 red-text">
This paragraph looks duplicated, can we make it one component

2018-09-11 07:23 UTC, yeenab commented on src/components/SignUpForm/index.js
> +              <a href="https://reactjs.org/docs/thinking-in-react.html">
Why are we going to a `Thinking in React link`?

2018-09-11 07:23 UTC, yeenab commented on src/containers/SignUp/__test__/actions.test.js
> +      user: {
Can we create a file that contains our `test_data` and call it in all our tests

2018-09-11 07:23 UTC, yeenab commented on src/containers/SignUp/__test__/index.test.js
> +//     expect(wrapper.find("<SignUpForm/>").length).toEqual(1);
Is this commented code 😢

2018-09-11 07:43 UTC, asamisellah commented on src/components/SignUpForm/index.js
> +              <a href="https://reactjs.org/docs/thinking-in-react.html">
At the time I didn't have the sign in page link but I will change that

2018-09-11 07:43 UTC, asamisellah commented on src/containers/SignUp/__test__/actions.test.js
> +      user: {
yes, that's possible

2018-09-11 07:44 UTC, asamisellah commented on src/containers/SignUp/__test__/index.test.js
> +//     expect(wrapper.find("<SignUpForm/>").length).toEqual(1);
I've actually made a couple of changes to this feature. I will get rid of all commented code

2018-09-11 12:03 UTC, asamisellah commented
@j33n I have made the requested changes

2018-09-12 06:06 UTC, yeenab approved these changes
LGTM

2018-09-12 06:06 UTC, merged